# Define the services (containers) that make up your application
services:
  # The NEW Hardhat Blockchain Node Service
  hardhat:
    build:
      context: .
      dockerfile: packages/hardhat/Dockerfile
    ports:
      - "8545:8545"
    # This command tells Docker to run our new startup script
    command: sh -c "cd packages/hardhat && ./entrypoint.sh"
    container_name: onchain-hardhat-node

  # The Backend Service
  backend:
    # Tell Docker Compose to build this image from a Dockerfile
    build:
      # The context is the root of our monorepo
      context: .
      # Specify the location of the backend's Dockerfile
      dockerfile: apps/backend/Dockerfile
    # Map port 3001 on your computer to port 3001 inside the container
    ports:
      - "3001:3001"
    # Add environment variables for other services
    environment:
      - MONGO_URI=${MONGO_URI}
      # This tells the backend to wait for the hardhat service to be ready before starting
    depends_on:
      - hardhat
    # Name the container for easy identification
    container_name: onchain-backend

  # The Frontend Service
  frontend:
    # Tell Docker Compose to build this image from its Dockerfile
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    # Map port 3000 on your computer to port 3000 inside the container
    ports:
      - "3000:3000"
    # This tells the frontend to wait for the backend service
    depends_on:
      - backend
    # Name the container
    container_name: onchain-frontend

volumes:
  mongo-data:
