/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/institutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the list of all the institutions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The list of the institutions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Institution"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new credit institution */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Institution"];
                };
            };
            responses: {
                /** @description The institution was successfully created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Institution"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions/{institutionId}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a CSV of loans for a specific institution */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution ID */
                    institutionId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description CSV processed successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Institution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions/{institutionId}/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all loans for a specific institution */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution ID */
                    institutionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of loans */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Loan"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/institutions/dashboard/{institutionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a dashboard summary for an institution */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The institution ID */
                    institutionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard summary data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Institution not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/{loanId}/invest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Invest in a specific loan */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The loan ID */
                    loanId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        amountToInvest?: number;
                    };
                };
            };
            responses: {
                /** @description Successful investment */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Loan"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/loans/update-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update status of all expired loans */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Loan statuses updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Institution: {
            /** @description The auto-generated id of the institution */
            _id?: string;
            /** @description Name of the credit institution */
            name: string;
            /** @description Country where the institution is based */
            country: string;
            /** @description The year the institution was founded */
            foundingYear: number;
            /** @description Total portfolio value in EUR */
            totalPortfolio?: number;
            /** @description Risk score from 0 to 100 */
            creditRiskScore?: number;
            /**
             * @description Main product type
             * @enum {string}
             */
            productType: "Mortgage" | "Private" | "Business";
            /** @description Official website URL */
            websiteUrl?: string;
            /** @description Contact information */
            contacts?: string;
            /**
             * Format: date-time
             * @description The date the record was created
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description The date the record was last updated
             */
            updatedAt?: string;
        };
        Loan: {
            /** @description The auto-generated id of the loan */
            _id?: string;
            /** @description The ID of the parent institution */
            institution: string;
            /** @description The business-specific ID from the CSV file */
            loanId: string;
            /** @description The on-chain classId for the loan */
            classId: number;
            /** @description The on-chain nonceId for the loan */
            nonceId: number;
            /** @description Type of the loan */
            loanType?: string;
            /**
             * @description Current status of the loan
             * @enum {string}
             */
            status?: "ACTIVE" | "EXPIRED" | "PAID";
            /** @description The principal amount of the loan in EUR */
            principalOpenEur: number;
            /** @description The amount invested in the loan so far */
            investedAmount?: number;
            /**
             * Format: date-time
             * @description The expiration date of the loan
             */
            loanLastDate?: string;
            /** @description URL reference from the CSV, typically for on-chain data */
            url?: string;
            /**
             * Format: date-time
             * @description The date the record was created
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description The date the record was last updated
             */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
